/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.mdd2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TurtlesUiModule extends AbstractTurtlesUiModule {

	public TurtlesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
