/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.mdd2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TurtlesStandaloneSetup extends TurtlesStandaloneSetupGenerated {

	public static void doSetup() {
		new TurtlesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
